### ISSUE TITLE
Обновление пакетов

### ISSUE THREAD

**Issue by semeleven** [webmaza75/material-ui#10]
в https://github.com/webmaza75/material-ui/pull/9 произошло обновление TS, что не может не радовать, но кажется, что стоит обновить не только TS, но и остальные пакеты. Например, заботливый github сам предлагает обновить lodash и handlebars

**Comment by webmaza75** [comment]
Обновила lodash и handlebars

**Comment by semeleven** [comment]
А почему остальные пакеты не обновили? React тот же самый

**Comment by webmaza75** [comment]
Исправлено #14 (Обновление пакетов и u-тестов, fix в типизации).
